package com.troyka.recargas.entity;
// Generated 11/07/2022 01:07:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private BigDecimal idFactura;
     private Vendedor vendedor;
     private Recarga recarga;

    public Factura() {
    }

    public Factura(BigDecimal idFactura, Vendedor vendedor, Recarga recarga) {
       this.idFactura = idFactura;
       this.vendedor = vendedor;
       this.recarga = recarga;
    }
   
    public BigDecimal getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(BigDecimal idFactura) {
        this.idFactura = idFactura;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public Recarga getRecarga() {
        return this.recarga;
    }
    
    public void setRecarga(Recarga recarga) {
        this.recarga = recarga;
    }




}


