package com.troyka.recargas.entity;
// Generated 11/07/2022 01:07:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Recarga generated by hbm2java
 */
public class Recarga  implements java.io.Serializable {


     private BigDecimal idRecarga;
     private String operador;
     private double valorMinuto;
     private BigDecimal cantidad;
     private double total;
     private Set facturas = new HashSet(0);

    public Recarga() {
    }

	
    public Recarga(BigDecimal idRecarga, String operador, double valorMinuto, BigDecimal cantidad, double total) {
        this.idRecarga = idRecarga;
        this.operador = operador;
        this.valorMinuto = valorMinuto;
        this.cantidad = cantidad;
        this.total = total;
    }
    public Recarga(BigDecimal idRecarga, String operador, double valorMinuto, BigDecimal cantidad, double total, Set facturas) {
       this.idRecarga = idRecarga;
       this.operador = operador;
       this.valorMinuto = valorMinuto;
       this.cantidad = cantidad;
       this.total = total;
       this.facturas = facturas;
    }
   
    public BigDecimal getIdRecarga() {
        return this.idRecarga;
    }
    
    public void setIdRecarga(BigDecimal idRecarga) {
        this.idRecarga = idRecarga;
    }
    public String getOperador() {
        return this.operador;
    }
    
    public void setOperador(String operador) {
        this.operador = operador;
    }
    public double getValorMinuto() {
        return this.valorMinuto;
    }
    
    public void setValorMinuto(double valorMinuto) {
        this.valorMinuto = valorMinuto;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


